language: rust
rust:
- stable
- beta
- nightly

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script: 
- | 
  cargo build --verbose
  cargo test --verbose
  travis-cargo --only stable doc

matrix:
  allow_failures:
  - rust: nightly
env:
  global:
    secure: lOYWHkB+TqKwZVj3HrgK2dXMrKjd55tfR0DfAEqmLvbo+YEPWCy0dK8p5eAWIePWsH6DsWeW+AmizOcbJwYPOSunRWOL8SznFb5keQ0z7SG65lP2Ifi6RtlENsFOu0EwXm1ZknE1j97YCo6VBpernmWvYOVOajL4vK4TXoYKCG1vIkPJEvSNFJhABRUTwVnsqWuDB3bBWCic1UQHFukqvfc4jWVU746cQUNxypU0Ij6pYVSNFFrj9THNVLRIC3bEdOUshcUOk4+c9dp19XxRIcKiH2qcWf5TMWcpPpSzsWki0UWnHCPgMWrxrY9cIsCiAjOKvMemK8yiHBvrQ30upxiKLVzVjSohD4F3Zjama+AdVdpfIxN+w7xYTTlcYy2yMxrnyry5EiaILVtBSHG6qKAYI+bT6gnaPHkvTCDoVRLcgDek5dGZ5KS/FULqMVOuJW6jGaUX+XUvcUrwYTy+ZERpbeDczHt6z7Ko6LGCjP5wOjC9Tmcy04YCRf92sfpWtYwsT+W0RS6Tkg1ydE6iY+mZBWzdosN6GJ4ZRmldUYlvR36mt42xqPYvwxf04ewIQyyl6n96iIqNd8DEXTOSBDLRPuaWKEIRcMnP7hSNs/vjmmRipB0aj1r+FiGFhMT+gLjdZtKWT3we+a2jwBDWaWBRc2iHYiX4BAkXji3pkOQ=
